### ISSUE TITLE
Corriger le format du permalink

### ISSUE THREAD

**Issue by daamien** [postgresqlfr/blog.postgresql.fr#2]
@xlii-chl, 

Le nouveau format de permalien ne me convient pas: 

Le paramètre 

```
permalink: /:categories/:year/:title:output_ext
```

produit des URL comme ça: 

https://testblog.postgresql.fr/2019/postgresql%20weekly%20news/2019/nouvelles-hebdomadaires-de-postgresql-22-decembre-2019.html

ce qui me fait dire que: 

* Le `:year` est inutile parce qu'on fait déjà un découpage par année et donc l'année sera déjà présente dans l'URL

* ça me dérange d'avoir la catégories dans l'URL parce que 90% des articles viennent de la même catégorie... Et il y a un risque qu'un auteur mette un catégorie trop longue et que l'URL deviennent illisible...  Par exemple, là vu qu'il y a des espaces dans la catégorie "postgresql weekly news" ça se transforme en `%20` et c'est pas très élégant...

Je propose de simplifer et mettre simplement:

```
permalink: /:title:output_ext
```

ou revenir à la forme précédente...

**Comment by xlii-chl** [comment]
Ok pour moi.

Par contre, sur mon instance locale, en ne mettant que `/:title:output_ext`, l'année n'apparaît pas dans l'URL et tous les posts se trouvent à la racine de `_site`.

**Comment by xlii-chl** [comment]
Au fait, autre proposition de modification des URL de pagination : bf9ebb5d2e56dcca4c7d54dbb36a9d1f93d7c18f

**Comment by daamien** [comment]
ok pour la pagination, ça me va...

Je confirme que le comportement du paramètre `permalink` bizarre 

J'ai mis `permalink: /:year/:title:output_ext` et j'obtiens ça:

/2020/nouvelles-hebdomadaires-de-postgresql-1er-mars-2020.html

si ça te va on peut partir là-dessus...

**Comment by xlii-chl** [comment]
Oui, nickel. Merci !
