### ISSUE TITLE
Le feed RSS ne se met pas à jour 

### ISSUE THREAD

**Issue by daamien** [postgresqlfr/blog.postgresql.fr#8]
La version actuel pointe vers testblog:

https://blog.postgresql.fr/feed.xml

cc @xlii-chl

**Comment by xlii-chl** [comment]
Hello,
je retombe sur cette issue : a priori, problème résolu.
- côté [blog](https://blog.postgresql.fr/), le feed fonctionne et le header `<link type="application/rss+xml">` est bon,
- côté [portail](https://www.postgresql.fr/), le bloc _Actualité_ se met bien à jour (le bloc _Planète_ n'a pas l'air d'inclure le blog, par contre).

Ticket fermable sauf contre-indication d'ici une semaine.
